---
apiVersion: v1
kind: Service
metadata:
  name: employees-service-go-service
spec:
  type: NodePort
  selector:
    service: employees-service-go
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 50002
      targetPort: http
